name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger the action on pushing to the 'master' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building multi-platform images

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Log in to Docker Hub using your credentials
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username from GitHub secrets
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # Your Docker Hub access token from GitHub secrets

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5  # Build and push the Docker image
      with:
        context: .  # Use the current directory as the context for building the image
        push: true  # Push the image to Docker Hub
        tags: sathwikreddy1/weather_dashboard_fixed:latest  # Replace with your Docker Hub username and image name
